- Catppuccin.theme.css
THIS IS AN IDEA.
I think that the cat should only appear when you hover over it.
------------
DEFAULT
----------
ON HOVER
> Remove the shadow cat

- Catppuccin.theme.css
This is my first ever github pull request so if i screwed it up I'm sorry
I fixed some simple issues with colours:
Fixed the colour of:
the "Unread Channels" button,
the "You're viewing old messages" button,
the navigation bar when using CTRL+K or "find or start a conversation" in the top right,
and the "currently applied search filters" background colour.
I also completely did the search section in the top right corner
I'm not certain about the colour of this one yet:
the Unread button
> Fixed some issues regarding UI colours

- Catppuccin.theme.css
- README.md
1. Fixed thin scrollbars. Discord's default theme doesn't makes thin scrollbars track's colored, so I made it transparent. Making it different from transparent makes some visual bugs, for example we see scrollbar at server header popup.
2. Fixed server modals, boost page.
3. Fixed emoji popups. (From #11, thank you @andreasgrafen)
> some fixes

- .editorconfig
- Catppuccin.theme.css
This aims to fix everything discussed in #12.
> Refactor for better Maintainability

- discord.user.css
> Update forum and home background

- discord.user.css
> Login Box background and discover guilds thing background

- README.md
- main.css
Title. Frankly, a few more changes could be in order for the readme, but i'll leave that for a different pull.
> fix: forum Channel, add GooseMod instructions

- dist/catppuccin-frappe.theme.css
- dist/catppuccin-latte.theme.css
- dist/catppuccin-macchiato.theme.css
- dist/catppuccin-mocha.theme.css
- src/_theme.scss
> fix: missing background in delete message popout

- src/_theme.scss
- removed red highlight when hovering over the emoji in the message bar
- colored live shape
> fix: emojis in chatbar, "LIVE" button text

- dist/catppuccin-frappe.theme.css
- dist/catppuccin-latte.theme.css
- dist/catppuccin-macchiato.theme.css
- dist/catppuccin-mocha.theme.css
- src/_theme.scss
- Themed reaction and server boost page
- Patched unthemed stuff (that I could find)
> feat: fixes and additions

- src/components/_pages.scss
> Fix App Discovery Background

- src/components/_popouts.scss
> feat: hover on context menu buttons

- src/components/_details.scss
- src/components/_popouts.scss
> fix: Search bar calendar

- src/components/_popouts.scss
> fix: Calendar popout hint button text

- src/components/_popouts.scss
> fix: user volume slider

- src/components/_popouts.scss
> fix: theme format popup + make caret curst when hover

- src/components/_catppuccin-server.scss
Themes role colors in typing indicators to appropriate flavor-dependent colors
> feat: vencord enhanced typing indicator theming

- src/components/_details.scss
Badge now is proper color. Found by Tnixc in the discord, thx for reporting!
> fix: activities try it out badge

- src/components/_buttons.scss
> fix: recolor radio buttons

- src/components/_popouts.scss
> fix: Latte text for gif categories

- src/components/_popouts.scss
> Fix links being uncolored in user popouts on latte

- src/components/_popouts.scss
See discord:
https://discord.com/channels/907385605422448742/1020555849372012635/1100421882358013972
> Fix: user popout

- src/components/_chat.scss
Woo mentioned in the discord
it worky now
> Fix spoiler tags

- src/components/_chat.scss
> fix: Too many files popup

- src/components/_chat.scss
It didn't use to use accent. Also i fixed a bug I introduced in https://github.com/catppuccin/discord/commit/c1480400345233ac43b9109efce5c6a728196f7a, I hardcoded the red value lol
> fix: Bot slash command selected field should use accent

- src/components/_chat.scss
> fix: Jump to Present Bar text

- src/components/_popouts.scss
> fix: Discord server invite popup

- src/components/_popouts.scss
> fix: Quickswitcher ping badge

- README.md
This PR adds a section to the README explaining how to install the theme using [BeautifulDiscord](https://github.com/leovoel/BeautifulDiscord).
> docs: add instructions for installation using BeautifulDiscord

- src/components/_chat.scss
- src/components/_sidebar.scss
> fix: qualityIndicatorBadge background color

- src/catppuccin-latte.theme.scss
- src/components/_buttons.scss
- src/components/_chat.scss
- src/components/_details.scss
- src/components/_navbar.scss
- src/components/_pages.scss
- src/components/_popouts.scss
- src/components/_sidebar.scss
- src/components/_variables.scss
Attempt 2 electric boogaloo, if someone could triple check for me, that would be ideal. I also fixed a bug i introduced (oops) where the friend request badge would only be mocha crust since thats so minor and shouldn't be in for any longer than it needs to be.
> feat: Switch all caret selectors to pipes

- src/components/_details.scss
Before:
After:
Reset the 2 week streak of discord not having a single bug
> fix: Forum channel pins

- src/components/_popouts.scss
Broken:
Fixed:
Thanks to @chiefjazzdiewltr for pointing this out :3
> fix: Search bar coloring

- src/components/_popouts.scss
https://github.com/catppuccin/discord/issues/131#issuecomment-1646819384 but without breaking the format popup.
> fix: Close button of text chat in voice channels

- src/components/_chat.scss
My sanity will dwindle more and more as the places i find these in will get more and more niche
I will find every bug in every corner of this hell
Before:
After:
> fix: Watch together chat ping badge in DMs

- src/components/_pages.scss
Discord is trying to psyop me into thinking things i've looked at nearly daily for weeks have been unthemed for just as long by breaking shit at random
you will not trick me evil demons
Before:
After:
> fix: input sensitivity bar

- package.json
- yarn.lock
Fixes hljs diff not showing up as catppuccin colors
> chore: bump catppuccin/highlightjs

- src/components/_variables.scss
Yadda yadda sanity dwindling whatever i'm too tired to spaz out over this
this also fixes the hljs diff thing not updating because the workflow doesn't run if you change package.json
before:
after:
> fix: privacy & safety radio bars

- src/components/_chat.scss
> fix: checkboxes in browse channels

- src/components/_buttons.scss
> fix: outlined buttons

- src/components/_popouts.scss
Txnic is really kicking my ass with this bughunting lmao
Having fun tho
Before:
After:
> fix: Clyde user popout

- src/components/_chat.scss
Because of course I check after i commit!
> fix: Forum channels without tiles background

- src/components/_chat.scss
- src/components/_pages.scss
- src/components/_popouts.scss
And also fix making the embeds the color of the background oopsie
> Fix more of tnixc's bugs

- src/components/_chat.scss
I remembered the pipe this time
If i find any more bugs I'll fix em tomorrow i'm screwing things up
> fix: Members bar fill to bottom

- src/components/_pages.scss
- src/components/_popouts.scss
Fix the switches being the wrong color when turned off, and fix checkboxes having light colored checks when on.
> fix: Tnixc bug collection 3

- src/components/_buttons.scss
- src/components/_chat.scss
- src/components/_details.scss
- src/components/_icons-bgImg.scss
- src/components/_icons-imgContent.scss
- src/components/_icons-svgBg.scss
- src/components/_icons-svgColor.scss
- src/components/_navbar.scss
- src/components/_pages.scss
- src/components/_popouts.scss
- src/components/_sidebar.scss
- src/components/_variables.scss
Seems like discord broke pretty much every theme by changing all the dashes separating their real class names from their random suffix. Good thing we use attribute selectors!
> Fix: Most of the major stuff discord broke

- src/components/_chat.scss
Oops surprised this is the only issue with what i did *foreshadowing*
> Fix: Undark hover buttons

- README.md
- src/components/_chat.scss
- src/components/_popouts.scss
- src/components/_variables.scss
- Shift + Enter on forum channels
- Reactions on forum channels
- Flowerstar icons on servers
- Unborked reactions
>  Fix: another round of tnixc's bugs

- src/components/_chat.scss
- src/components/_pages.scss
- src/components/_popouts.scss
- src/components/_variables.scss
Discord has like 7 different ways of applying svgs in the app and i feel like i'm about to scribble SVG in a slowly deterioring repeating circular pattern on my floor to sacrifice a thinkpad to the discord gods to normalize how they apply svgs
> fix: a lot of terrible SVG jank

- src/components/_popouts.scss
> fix: phone number area code popout

- src/components/_pages.scss
Fix a lot of random bugs that Genshibe found. Thanks!
> fix: Server discovery configuration pages and server switches

- src/components/_details.scss
Quite possibly the worst thing I've ever done in the theme. Comments explain.
> fix: Explore discoverable servers button

- src/components/_navbar.scss
- src/components/_popouts.scss
> fix: Student hub icon and create server/discovery selected icons

- src/components/_pages.scss
Finally something not found by tnixc, thanks tycrek
> fix: Role reset button

- src/components/_buttons.scss
- src/components/_chat.scss
- src/components/_pages.scss
- src/components/_popouts.scss
Yep everything in #255 this took too long anyways its done yay i blacked out for about 2 hours doing this
> fix: everything in #255

- src/components/_sidebar.scss
IT IS DEAD
GOOD RIDDANCE
YOU'RE WELCOME TNIXC
> fix: Users in voice icon

- src/components/_chat.scss
- src/components/_details.scss
- src/components/_popouts.scss
- src/components/_variables.scss
- Event new badge
- markdown spoilers
- formatting iconbar
- offline circle in large profile popout
-  latte gif picker
closes #264
> 5 buncha fix

- src/components/_chat.scss
- src/components/_details.scss
- src/components/_popouts.scss
- Server Members page nav (Thanks tycrek)
- Invites revoke invite button (Thanks tycrek)
- Vencord toasts
- Loading splash keybinds (Thanks Tnixc)
> fix: 4 various fixes

- src/components/_details.scss
So it turns out I fixed this in my personal fork of the theme before I became the maintainer of the theme, sooooo this never got merged in! isn't that grand
> fix: call buttons

- src/components/_chat.scss
- src/components/_details.scss
- src/components/_pages.scss
I finally found the "Hey there tab friend" thing
> fix: hopefully all the key icons

- src/components/_chat.scss
- src/components/_details.scss
- src/components/_pages.scss
I still can't get tab friend to show up again so i'll solve this again tomorrow when i do another stream of tnixc bugs
> fix: revert the oopsie with the stupid keys

- src/components/_details.scss
https://github.com/Vendicated/Vencord/commit/799e6e7292c9ce2e5c678c0efeda1eadab2721be
> fix: vencord platform indicators

- src/catppuccin-frappe.theme.scss
- src/catppuccin-latte.theme.scss
- src/catppuccin-macchiato.theme.scss
- src/catppuccin-mocha.theme.scss
- src/components/_details.scss
> fix: new emoji icon and stop streaming button

- package.json
The fact this wasn't being done is equally funny and embarrassing
> ci: Minify releases

- pnpm-lock.yaml
- src/components/_chat.scss
Closes #282 
Also fixes browse channels tab not filling to bottom (3rd time i've fixed it, thanks discord)
> Welcome back

- src/components/_chat.scss
Fixes CSS applied SVGs for:
Leaving/Joining group DMs, Joining servers, Missing/Joining DM Calls
> fix: System message icons

- .github/workflows/gh-pages.yml
This'll allow you to test the workflow manually without needing to push changes to `src/*`
> ci: allow manual invocations

- src/components/_popouts.scss
a span is not a div
a span is not a div
a span is not a div
a span is not a div
a span is not a div
there teacher, I wrote my lines. Can I leave now?
> fix: reading labels is hard

- src/components/_details.scss
- src/components/_pages.scss
- src/components/_popouts.scss
- src/components/_variables.scss
Closes #324 among other things
> fix: GC typing icon + untheme title bar in VC + theme more keybinds + theme matchingPostsRow in forums

- src/components/_pages.scss
fixes a unthemed blue gradient on discord's discover page
> fix: gradient on discover page

- src/components/_variables.scss
> fix: properly theme brand buttons

- yarn.lock
This reverts commit 2f2f724de27275cd949bc81f4420edb543fc7efe.
> Revert "chore(deps): update dependency sass to v1.80.6 (#342)"

- src/components/_details.scss
- src/components/_variables.scss
- src/components/tweaks/_dark.scss
- src/components/tweaks/_light.scss
why the hell do these use different vars..
> forum fixes/switch animations/tooltip and vesktop screenshare contrast

- src/components/_details.scss
- src/components/_variables.scss
> fix: borders and frames
