main.css

Before `scrollbar-auto-scrollbar-color-thumb` and `scrollbar-auto-scrollbar-color-track` had the same value(`black3`) so you couldn't see where the scrollbar was unless you hovered over it.

Changed scrollbar color so it is visible

---

src/components/_popouts.scss

Fixes #54, while @nekowinston suggested a fix in the issue, that would mean discord light mode popouts would be set to dark mode style. This fix does not interfere with setting them to darkmode style, while also fixing the text being illegible.
With synced profile themes, Winstons solution (Fix applied, is not different than without the fix since it removes the `theme-light` class):
Without the fix:
Without synced profile themes (Fix given by this PR):

fix: Light theme nitro popout text is illegible

---

src/components/_popouts.scss

Whoopsie, the 3 people i tested for making the other pull all didn't have a status set. My bad!

fix: Light theme nitro popout status text illegible

---

src/components/_buttons.scss

Colors shuffle and repeat colors to match their state<br>
Shuffle and repeat turned off:
Shuffle and repeat turned on:
Repeat single track:

Add vencord spotify plugin theming

---

src/components/_details.scss

fix: Friends pending ping badge text color

---

.github/workflows/gh-pages.yml
README.md
build.js
package.json

Sharing what I did for [voidppuccin](https://github.com/nekowinston/voidppuccin-discord).
This will allow ctp to host all accent variants.
```css
/* latte (mauve) */
@import url("https://catppuccin.github.io/discord/dist/catppuccin-latte-mauve.theme.css");
...
```
I have this hosted in my fork, you can test using following,
```css
/* mocha (mauve) */
@import url("https://griimick.github.io/discord/dist/catppuccin-mocha-mauve.theme.css");
...
```
If this is fine, then might have to add a line about this in docs.

feat: generate and host accents

---

src/components/_details.scss

<code> foreignObject > rect</code> works instead of <code>foreignObject > div</code> but I've still kept that incase it does apply somewhere

fix: offline status indicator color

---

src/components/_popouts.scss

Before
After
Now using crust! This also solves #130.

fix: Warning card popout text

---

src/components/_details.scss
src/components/_popouts.scss

Fixes those issues:
- user indicators not being themed:
- some headers in popouts having a background color set when they shouldn't:

fix user status indicators and some popout headers

---

src/components/_chat.scss

fix: empty thread message error border

---

src/components/_popouts.scss

fix: prevent style leaking to user popout

---

src/components/_popouts.scss

On browser, there is a button at the bottom of the server scroller that opens a menu that was pretty much only themed by some residual css. Unfortunately, the svg images are loaded via css, and not embedded in the html. This means without recoloring and hosting the svgs (which is likely against some license) they must remain the colors they are.
Before: 
After:

fix: unthemed browser client download popout

---

src/components/_details.scss
src/components/_popouts.scss

Before:
After:
I Also noticed while I was working it out that the Number badge directly above it could use the `|=` selector as well so figured I'd just lump it in :3

fix: Channels & Roles text badge

---

src/components/_details.scss

Follows accent color as it should to match other bot tags :>

fix: Clyde AI bot tag

---

src/components/_popouts.scss

Before:
After:
Fixed a few more `^=` -> `|=` around it as well, we'll get there with enough bugs lol

fix: Friend Menu Pending Badge

---

src/components/_details.scss

fix: Add Friend input box border should use accent

---

src/components/_details.scss

fix: vencord theme input border should use accent

---

src/components/_details.scss

Because of *course* they changed it into an inline style!

fix: New Channel badge has wrong background

---

src/components/_details.scss

Proof catppuccin users don't have friends that this hadn't been found yet :woeis:

fix: Pending friend request badge button

---

src/components/_chat.scss

fix: Call buttons are the wrong color

---

src/components/_chat.scss

Fixes unthemed members tab shown by @notashelf

fix: members tab does not fill to bottom

---

src/components/_navbar.scss

fixes navbar elements illegible text on hover and active
before:
after:

fix: navbar elements text color on `:hover` and active

---

src/components/_navbar.scss

before:
after:
should fix:
1. add a server
2. explore discoverable servers
3. download apps
small oof, forgot to delete this line last time

fix: navbar elements background on `:hover`

---

src/components/_pages.scss

before: 
after:
fixes search text in https://discord.com/guild-discovery

fix: *find your community* search text

---

src/components/_buttons.scss
src/components/_chat.scss
src/components/_popouts.scss

As the Discord dev, I toil and I strive,
Fixing bugs so they won't come alive.
But they keep coming back,
Like a never-ending track,
And my sanity, I fear, takes a dive.
Before:
After:
Before:
After:
Before:
After:
Before:
After:
Before:
After:

fix: A lot of stage channel bugs & the account switcher

---

src/components/_chat.scss

No pictures because it's self explanatory how did discord even screw this up

fix: Forum channels background

---

src/components/_pages.scss

And one more of tnixc's bugs for the road
i'm tired
here's what it looked like before, now it actually looks right
idk breaking the embeds spooked me so now i'm just <a:KEK:1102995183739613224>

fix: nitro profile picture upsell button

---

src/components/_popouts.scss

the text was white before now its not yippee

fix: Keybinds popout text

---

src/components/_chat.scss

Now it fills to the bottom waow

fix: Members bar fill to bottom

---

src/components/_popouts.scss
src/components/_variables.scss

This now properly uses accent
These are now crust

Fix: streaming setting selectors and unthemed role link button

---

src/components/_chat.scss

Due to not looking around enough on fixing the Forum channel header icons, turns out it also affected some video play buttons.

fix: miscolored video play buttons

---

src/components/_popouts.scss

Oops the icon lock didn't work because I hardcoded the popout id haha isn't it cool how it only randomizes on reload not on opening and closing

fix: popouts have randomized id

---

src/components/_chat.scss
src/components/_popouts.scss

The caret is crust now
These are now properly green.
leave arrows, and missed and joined call icons are now properly colored as well.

fix: various css embedded svgs and danger menu carets

---

src/components/_pages.scss

This thing actually animates right now

fix: boost progress bar animation

---

src/components/_chat.scss

Oops that shouldn't have slipped for so long

fix: Reaction numbers glow on hover

---

src/components/_chat.scss
src/components/_popouts.scss

Fixes the color selector for changing folder and user banner color, as well as the caret found when you are watching more than 1 stream, and also fixed the new clips enabled indicator because that's new

fix: Color Selector Popout and Stream select caret

---

src/components/_details.scss

The newest Discord update changes the color of the user status badges, so I've updated the CSS rules so they match again.

fix: match new status badge colors

---

.github/workflows/gh-pages.yml

#291 is still in the air, but in the meantime I'm just gonna bump these, the theme builds on node 21 on my machine so 20 (what v4 actions run on) should be fine.

chore: bump CI

---

src/catppuccin-frappe.theme.scss
src/catppuccin-latte.theme.scss
src/catppuccin-macchiato.theme.scss
src/catppuccin-mocha.theme.scss

Our own Highlight.js port sets the selector to `code ...`, which works for code blocks in sent messages but not in the text input box. We can change this selector ourselves, which is what this PR does.
| Before | After |
| --- | --- |
| ![CleanShot 2024-06-17 at 15 14 50@2x](https://github.com/catppuccin/discord/assets/47499684/a0157335-6a48-4255-821d-ff9a3c37fb03) | ![CleanShot 2024-06-17 at 15 19 52@2x](https://github.com/catppuccin/discord/assets/47499684/a897438b-e4a2-4a7b-8be3-0e1032239809) |

fix: theme syntax highlighting in message input box

---

src/components/_sidebar.scss

| Before | After |
| --- | --- |
| ![CleanShot 2024-07-03 at 22 46 23@2x](https://github.com/catppuccin/discord/assets/47499684/980b98b2-d6f6-4ca1-bbeb-872e3c7655e8) | ![CleanShot 2024-07-03 at 22 47 16@2x](https://github.com/catppuccin/discord/assets/47499684/d3a9ceca-53a1-4b6d-aa30-bd861234d7b1) |

fix: fade-out instead of mixing with text for rainbow threads

---

src/components/_chat.scss

Search results aren't contained within the `chatContent` element, but the audio/video controls still use the same classes, so it just needs to be moved outside the class.

Fix: Theme audio/video controls in search results

---

src/components/_details.scss

Fix: Make keybinds text in loading tip visible

---

src/components/_chat.scss
src/components/_variables.scss

`div[class*="pageBody_"]` is required to properly theme the Browse Channels tab.
As far as I can tell, the only thing that `div[class*="content_"][class*="container_"] { div[class*="container"] }` affects is the box around dropdowns in the Customise tab, so I've changed it to match the background colour of those prompts.
Closes #312

Fix: Theme channels & roles

---

src/components/_variables.scss

The background of the selected reply uses `--background-message-highlight` normally and `--brand-10a` when hovered.
Happens to theme the background of selected reactions too (`--brand-15a`)

fix: selected reply hover

---

src/components/_buttons.scss
src/components/_details.scss
src/components/_pages.scss

Closes #281. Also fixes the text colours of the G icon in "Go Live" when streaming, keybinds tab in settings, selected buttons in stream settings popup, and "Subscribe" in Nitro settings tab

fix: activity panel buttons colour + others

---

src/components/_details.scss

Apparently this has been [fixed in my fork](https://github.com/ToxicAven/discord/blob/90ea0d7d4e4c7fd0e1b0ef9ce99cac691c95e4a7/src/components/_aven.scss#L775-L778) of the theme for like a year, and I just never noticed it otherwise.
before
after
Thanks @rubyowo

Fix: remove embeds hover color

---

package.json

`husky install` is deprecated:
```
$ husky install
install command is DEPRECATED
```

chore(package.json): update husky prepare script

---

src/components/_sidebar.scss
src/components/_variables.scss
src/components/tweaks/_dark.scss

--bg-mod-* and --text-normal vars were dropped. despite this they are still in use by client mods so keep to prevent breakage
also fix a typo

update vars and fix typo

---

src/catppuccin-latte.theme.scss
src/components/tweaks/_light.scss

Discord did some stylesheet reordering that caused the dark vars to overwrite the light vars when in light mode.
fixes: #401
I have some changes in the works that should fix these stylesheet ordering issues entirely.

fix: light theme priority
